// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuiofrqjwwdamcwjtsqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1aW9mcnFqd3dkYW1jd2p0c3FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzA3NjYsImV4cCI6MjA2MjEwNjc2Nn0.IwdLz023dCBwkN7GL47QTYxik2sw-dIy2e-h8NlwKZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);